### ISSUE TITLE
Error when loading WordTransformer: ImportError: libcudnn.so.8

### ISSUE THREAD

**Issue by Alex-Astolfi** [pierluigic/xl-lexeme#3]
We get this error on a linux system with python 3.11: 

> >>> import WordTransformer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mount/arbeitsdaten20/projekte/cik/users/alex/xl-lexeme/WordTransformer/__init__.py", line 1, in <module>
    from .WordTransformer import WordTransformer
  File "/mount/arbeitsdaten20/projekte/cik/users/alex/xl-lexeme/WordTransformer/WordTransformer.py", line 11, in <module>
    import transformers
  File "/mount/arbeitsdaten20/projekte/cik/users/alex/internship2/lib/python3.11/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/mount/arbeitsdaten20/projekte/cik/users/alex/internship2/lib/python3.11/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/mount/arbeitsdaten20/projekte/cik/users/alex/internship2/lib/python3.11/site-packages/transformers/utils/__init__.py", line 33, in <module>
    from .generic import (
  File "/mount/arbeitsdaten20/projekte/cik/users/alex/internship2/lib/python3.11/site-packages/transformers/utils/generic.py", line 465, in <module>
    import torch.utils._pytree as _torch_pytree
  File "/mount/arbeitsdaten20/projekte/cik/users/alex/internship2/lib64/python3.11/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
>>>

**Comment by Alex-Astolfi** [comment]
We discovered it was likely due to the version of virtualenv used to create the environment in which the dependencies were installed (virtualenv 20.21.1).

In an environment created with virtualenv 20.26.1 and in anaconda environments the import works.
